# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aedda3e20a2b845d36e51832195a92d73bff98d64abeddcced0d336d7d8a811be41b50d9e8278e0552db88f17d7cdcdb8772312105e6adb56db656a9f02cb0d3

test:
  secret_key_base: 4b0f65efb23934de9b4b738123c6e8f05096ff536f85c74939db0cef43bdfe8683e357e00365103e5981528555bb3c17ae687af7374854dda776a9d5d98ac38e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
